/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordgenerator;
/**
 *
 * @author almarzooqih23
 */
public class PasswordGeneratorGUI extends javax.swing.JFrame {

    /**
     * Creates new form PasswordGeneratorGUI
     */
    public PasswordGeneratorGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        howlongLabel = new javax.swing.JLabel();
        howLongComboBox = new javax.swing.JComboBox<>();
        passwordTextFeild = new javax.swing.JTextField();
        generatePasswordButton = new javax.swing.JToggleButton();
        yourPasswordLabel = new javax.swing.JLabel();
        a_to_z_checkbox = new javax.swing.JCheckBox();
        A_to_Z_checkbox = new javax.swing.JCheckBox();
        zero_to_nine_checkbox = new javax.swing.JCheckBox();
        special_character_checkbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Generator");

        howlongLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        howlongLabel.setText("Password length:");

        howLongComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        passwordTextFeild.setEditable(false);

        generatePasswordButton.setText("Generate password");
        generatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePasswordButtonActionPerformed(evt);
            }
        });

        yourPasswordLabel.setText("Your password: ");

        a_to_z_checkbox.setText("a-z");
        a_to_z_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_to_z_checkboxActionPerformed(evt);
            }
        });

        A_to_Z_checkbox.setText("A-Z");

        zero_to_nine_checkbox.setText("0 - 9");
        zero_to_nine_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_to_nine_checkboxActionPerformed(evt);
            }
        });

        special_character_checkbox.setText("Special Characters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(generatePasswordButton)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(howlongLabel)
                        .addGap(54, 54, 54)
                        .addComponent(howLongComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(a_to_z_checkbox)
                        .addGap(36, 36, 36)
                        .addComponent(A_to_Z_checkbox)
                        .addGap(47, 47, 47)
                        .addComponent(zero_to_nine_checkbox)
                        .addGap(33, 33, 33)
                        .addComponent(special_character_checkbox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(yourPasswordLabel)
                        .addGap(12, 12, 12)
                        .addComponent(passwordTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howlongLabel)
                    .addComponent(howLongComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_to_z_checkbox)
                    .addComponent(A_to_Z_checkbox)
                    .addComponent(zero_to_nine_checkbox)
                    .addComponent(special_character_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourPasswordLabel))
                .addGap(18, 18, 18)
                .addComponent(generatePasswordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePasswordButtonActionPerformed
        // TODO add your handling code here:
        
        //Getting the user input.
        int howLong = Integer.parseInt(howLongComboBox.getSelectedItem().toString());
        Password password = new Password(howLong, a_to_z_checkbox.isSelected(),
                A_to_Z_checkbox.isSelected(), zero_to_nine_checkbox.isSelected(),
                special_character_checkbox.isSelected());
        password.generatePassword();
        passwordTextFeild.setText(password.getPassword());
    }//GEN-LAST:event_generatePasswordButtonActionPerformed

    private void a_to_z_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_to_z_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_to_z_checkboxActionPerformed

    private void zero_to_nine_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_to_nine_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zero_to_nine_checkboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordGeneratorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A_to_Z_checkbox;
    private javax.swing.JCheckBox a_to_z_checkbox;
    private javax.swing.JToggleButton generatePasswordButton;
    private javax.swing.JComboBox<String> howLongComboBox;
    private javax.swing.JLabel howlongLabel;
    private javax.swing.JTextField passwordTextFeild;
    private javax.swing.JCheckBox special_character_checkbox;
    private javax.swing.JLabel yourPasswordLabel;
    private javax.swing.JCheckBox zero_to_nine_checkbox;
    // End of variables declaration//GEN-END:variables
}
